/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LOGIN;

/**
 *
 * @author MARTI
 */
public class MENUX1 extends javax.swing.JFrame {

    /**
     * Creates new form MENUX
     */
    public MENUX1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LOGINV = new javax.swing.JButton();
        REGISTROV = new javax.swing.JButton();
        SALIRV = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 68)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(213, 213, 213))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 80));

        LOGINV.setText("LOGIN");
        LOGINV.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        LOGINV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINVActionPerformed(evt);
            }
        });
        jPanel1.add(LOGINV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 180, 60));

        REGISTROV.setText("REGISTRO");
        REGISTROV.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        REGISTROV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTROVActionPerformed(evt);
            }
        });
        jPanel1.add(REGISTROV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 180, 60));

        SALIRV.setText("SALIR");
        SALIRV.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        SALIRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRVActionPerformed(evt);
            }
        });
        jPanel1.add(SALIRV, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 180, 60));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGINVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINVActionPerformed
        this.setVisible(false);
        
        LOGINX1 TTT=new LOGINX1();
        
        TTT.setVisible(true);
        TTT.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_LOGINVActionPerformed

    private void SALIRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRVActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SALIRVActionPerformed

    private void REGISTROVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTROVActionPerformed
        this.setVisible(false);
        
        REGISTROX1 KKK=new REGISTROX1();
        
        KKK.setVisible(true);
        KKK.setLocationRelativeTo(null);
        
        
        
    }//GEN-LAST:event_REGISTROVActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGINV;
    private javax.swing.JButton REGISTROV;
    private javax.swing.JButton SALIRV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
