/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LOGIN;

import javax.swing.JOptionPane;

/**
 *
 * @author MARTI
 */
public class REGISTROX1 extends javax.swing.JFrame {

    /**
     * Creates new form REGISTROC
     */
    public REGISTROX1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        REGISTRARB1 = new javax.swing.JButton();
        VOLVERV1 = new javax.swing.JButton();
        MostrarPass = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 68)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(184, 184, 184))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, 40));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 190, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("USUARIO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("CONTRASEÑA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 130, 30));

        REGISTRARB1.setText("REGISTRAR");
        REGISTRARB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REGISTRARB1MouseClicked(evt);
            }
        });
        jPanel1.add(REGISTRARB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 160, 50));

        VOLVERV1.setText("VOLVER");
        VOLVERV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLVERV1ActionPerformed(evt);
            }
        });
        jPanel1.add(VOLVERV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 160, 50));

        MostrarPass.setBackground(new java.awt.Color(0, 0, 0));
        MostrarPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MostrarPass.setForeground(new java.awt.Color(255, 255, 255));
        MostrarPass.setText("Mostrar");
        jPanel1.add(MostrarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VOLVERV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLVERV1ActionPerformed
        this.setVisible(false);
        MENUX1 HHH=new MENUX1();
        
        HHH.setVisible(true);
        HHH.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_VOLVERV1ActionPerformed

    private void REGISTRARB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGISTRARB1MouseClicked
         if (!username.getText().isEmpty() && !password.getText().isEmpty()) {
            Creacion_Player1 users = new Creacion_Player1(username.getText(), password.getText());
            if (Player_Comprobante1.insert(users)) {
                JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Usuario ya existente");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Porfavor ingrese los datos requeridos");
        }
    }//GEN-LAST:event_REGISTRARB1MouseClicked

    
    private void MostrarPassActionPerformed(java.awt.event.ActionEvent evt) {                                            
        if (MostrarPass.isSelected()) {
            password.setEchoChar((char) 0);
        } else {
            password.setEchoChar('*');
        }
    }       
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox MostrarPass;
    private javax.swing.JButton REGISTRARB1;
    private javax.swing.JButton VOLVERV1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
